# Site settings
# These are used to personalize your new site.
title: Roderick L. Oliver # your name here
logo: "images/Photo_Shoot_Image_Cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Technology (class of 2022)
  <br /><br />
  <button type="button" class="btn btn-info"><a href="http://rodoliver.atwebpages.com/myResume/Resume.pdf">View My Resume</a></button>
  <br /><br />
  <button type="button" class="btn btn-info" onclick="window.location.href="https://www.linkedin.com/in/roderick-oliver">View My LinkedIn Profile</a></button>
repository: "rodoliver/rodoliver.github.io"
github_username:  rodoliver # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
remote_theme: tuur29/pages-themes-cayman
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

